import {Session,distance,segmentBlocked,recipe} from '../src/sim.js';
const DT=.025;
export function advance(m,seconds,input={x:0,z:0,action:false}){for(let t=0;t<seconds&&m.phase!=='finished';t+=DT)m.update(DT,input);}
function path(m,goal,stealth=false){const step=.5,bx=Math.floor(m.bounds.x*2/step),bz=Math.floor(m.bounds.z*2/step),toCell=q=>({x:Math.round((q.x+m.bounds.x)/step),z:Math.round((q.z+m.bounds.z)/step)}),toWorld=q=>({x:q.x*step-m.bounds.x,z:q.z*step-m.bounds.z});const start=toCell(m.player),end=toCell(goal),key=q=>q.x+','+q.z,queue=[start],cost=new Map([[key(start),0]]),parents=new Map(),done=new Set();let finish=null;
 const visible=p=>{if(m.bushes?.some(q=>distance(p,q)<q.r))return false;return [...(m.guards||[]),...(m.off>0?[]:m.cameras||[])].some(g=>{const d=distance(p,g),range=m.guards.includes(g)?3.3:g.range;const dot=(Math.sin(g.angle)*(p.x-g.x)+Math.cos(g.angle)*(p.z-g.z))/Math.max(.01,d);return d<range&&dot>.69&&!segmentBlocked(g,p,m.boxes);});};
 while(queue.length){queue.sort((a,b)=>(cost.get(key(a))+Math.hypot(a.x-end.x,a.z-end.z))-(cost.get(key(b))+Math.hypot(b.x-end.x,b.z-end.z)));const q=queue.shift(),k=key(q);if(done.has(k))continue;done.add(k);if(q.x===end.x&&q.z===end.z){finish=q;break;}for(const [dx,dz]of [[1,0],[-1,0],[0,1],[0,-1]]){const n={x:q.x+dx,z:q.z+dz};if(n.x<1||n.z<1||n.x>=bx||n.z>=bz)continue;const p=toWorld(n);if(m.boxes.some(b=>Math.abs(p.x-b.x)<b.w/2+.41&&Math.abs(p.z-b.z)<b.d/2+.41))continue;const nk=key(n),c=cost.get(k)+1+(stealth&&visible(p)?35:0);if(c<(cost.get(nk)??Infinity)){cost.set(nk,c);parents.set(nk,q);queue.push(n);}}}
 if(!finish)return [goal];const route=[goal];for(let q=finish;parents.has(key(q));q=parents.get(key(q)))route.unshift(toWorld(q));return route;
}
export function walkTo(m,goal,{action=false,stealth=false,threshold=.25,max=28}={}){let route=path(m,goal,stealth),age=0;for(let t=0;t<max&&m.phase!=='finished';t+=DT){if(distance(m.player,goal)<threshold){advance(m,.1,{x:0,z:0,action});return true;}if(stealth&&age>.40){route=path(m,goal,true);age=0;}while(route.length>1&&distance(m.player,route[0])<.3)route.shift();const q=route[0],d=distance(m.player,q);m.update(DT,{x:(q.x-m.player.x)/Math.max(d,.001),z:(q.z-m.player.z)/Math.max(d,.001),action});age+=DT;}return distance(m.player,goal)<threshold;}
function tap(m){advance(m,.04,{x:0,z:0,action:true});advance(m,.29);}
function cookPilot(m){for(let turn=0;turn<180&&m.phase!=='finished';turn++){
 if(m.hand?.ready){const q=m.orders.find(q=>q.active&&!q.done&&recipe(q.type,m.index).name===m.hand.recipe.name);if(!q)break;const j=m.orders.filter(q=>q.active&&!q.done).findIndex(a=>a.id===q.id),g=m.layout.customers[j];walkTo(m,{x:g.x,z:g.z-1.0});tap(m);continue;}
 if(m.hand){if(!m.hand.chopped){walkTo(m,{x:m.layout.prep.x,z:m.layout.prep.z+1.25});for(let prep=0;prep<4&&!m.hand.chopped&&m.phase!=='finished';prep+=DT){const dx=m.layout.prep.x-m.player.x,dz=m.layout.prep.z+1.25-m.player.z;m.update(DT,{x:Math.max(-1,Math.min(1,dx*2)),z:Math.max(-1,Math.min(1,dz*2)),action:true});}advance(m,.3);}const stove=m.stoves[m.hand.recipe.cooker];if(stove.job){advance(m,.25);continue;}walkTo(m,{x:stove.x,z:stove.z+1.25});tap(m);continue;}
 const ready=m.stoves.filter(s=>s.job?.ready).sort((a,b)=>b.job.age-a.job.age)[0];if(ready){walkTo(m,{x:ready.x,z:ready.z+1.25});tap(m);continue;}
 const order=m.orders.filter(q=>q.active&&!q.done).sort((a,b)=>a.patience-b.patience).find(q=>!m.stoves[recipe(q.type,m.index).cooker].job);if(order){const r=recipe(order.type,m.index),bin=m.layout.bins[r.type];walkTo(m,{x:bin.x,z:bin.z+1.25});tap(m);continue;}
 advance(m,.25);
 }return m;}
function gardenPilot(m){for(const q of m.garden.mirrors)if(q.solution!==null)for(let attempt=0;attempt<3&&q.state!==q.solution;attempt++)m.touch('mirror',q.id);if(m.light!==m.garden.sourceColor)m.touch('source');if(!m.shutterOpen)m.touch('switch');advance(m,1.25);return m;}
function heistPilot(m){if(m.index>=3)walkTo(m,m.key,{action:true,stealth:true,threshold:.50});for(const cage of m.cages){if(m.index>=8&&m.off<1)walkTo(m,m.switch,{action:true,stealth:true,threshold:.65});walkTo(m,{x:cage.x,z:cage.z+.85},{action:true,stealth:true,threshold:.2,max:38});advance(m,1,{x:0,z:0,action:true});}walkTo(m,m.exit,{action:true,stealth:true,threshold:.4,max:38});return m;}
function racePilot(m){for(let t=0;t<m.budget&&m.phase!=='finished';t+=DT){const q=m.course.gates[m.score],p=m.player,d=distance(p,q);m.update(DT,{x:(q.x-p.x)/Math.max(d,1),z:(q.z-p.z)/Math.max(d,1),action:false});}return m;}
function partyPilot(m){let target=null;for(let t=0;t<70&&m.phase!=='finished';t+=DT){const p=m.player,bombs=m.fruit.filter(f=>!f.done&&f.kind==='bomb'&&f.duration-f.age<.45&&distance(f,p)<1.4);if(bombs.length){const b=bombs[0],dx=p.x-b.x,dz=p.z-b.z,d=Math.hypot(dx,dz)||1;m.update(DT,{x:dx/d||1,z:dz/d,action:false});continue;}const candidates=m.fruit.filter(f=>!f.done&&f.kind!=='bomb'&&(m.request===null||f.kind==='gold'||f.type===m.request));candidates.sort((a,b)=>{const merit=f=>(f.duration-f.age)*.5+distance(f,p)/4-(f.kind==='gold'?.4:0);return merit(a)-merit(b);});target=candidates[0];if(!target){m.update(DT,{x:0,z:0,action:false});continue;}const tx=Math.max(-4.1,Math.min(4.1,target.startX+m.wind)),dz=target.z-p.z,dx=tx-p.x,d=Math.hypot(dx,dz);m.update(DT,{x:dx/Math.max(1,d),z:dz/Math.max(1,d),action:d<1.05});}return m;}
export function pilot(mode,index){const m=new Session(mode,index);advance(m,2.5);return [cookPilot,gardenPilot,heistPilot,racePilot,partyPilot][mode](m);}
if(process.argv[1]?.endsWith('route-pilots.mjs'))for(let mode=0;mode<5;mode++)for(let i=0;i<15;i++){const m=pilot(mode,i);console.log(JSON.stringify({mode,level:i+1,won:m.won,remaining:Math.round(m.remaining),score:m.score,total:m.total,mistakes:m.mistakes,reason:m.reason,hand:m.hand?.recipe.name}));}
