export const GAMES=[
 {id:'bento-bears',name:'Bento Bears',animal:'MOMO / PANDA CHEF',genre:'COOK & MANAGE',color:'#ff694b',bg:'#ffd8bb',ink:'#632c30',icon:'◒',tag:'Small kitchen. Big delicious plans.',pitch:'Prep, cook and serve. Keep every little guest smiling.',action:'INTERACT',verb:'TAP / HOLD TO PREP',help:'Take an ingredient, use its cooker, collect the ready dish, then serve a matching guest. Hold at PREP to chop vegetables.',features:['One recipe, one happy guest','A second recipe joins the menu','Serve a small queue','Two cookers, two jobs','Chop before you cook','Watch the ready-food timer','Unlock the soup kettle','Avoid the kitchen spill','Three guests want different dishes','Shorter guest patience','A moving preparation trolley','Steam, simmer and fry together','A mixed afternoon rush','Plan around slippery corners','The grand tasting menu']},
 {id:'prism-garden',name:'Prism Garden',animal:'LUMA / LITTLE DEER',genre:'LIGHT & LOGIC',color:'#6546db',bg:'#dbd4ff',ink:'#34246c',icon:'✧',tag:'Turn a little light into a blooming world.',pitch:'Turn mirrors, split light and wake every sleepy flower.',action:'HINT',verb:'TAP MIRRORS TO TURN',help:'Tap mirrors directly. Light must touch every flower at once in its matching color. Follow the moving arrows. HINT highlights one next step; UNDO reverses your last move. Take your time — no countdown.',features:['Tap one mirror to wake your first flower','Follow the zigzag','Find the hidden turn','Three mirrors, one bloom','Ignore the spare mirror','Choose the right light color','Color filters change the beam','Four turns and two blooms','Find the route through the garden','A splitter feeds two paths','Open the sun shutter','Light three sleepy flowers','Some mirrors have a blocked side','Combine filters and split light','The full-spectrum garden']},
 {id:'pocket-heist',name:'Pocket Heist',animal:'RUE / RACCOON SCOUT',genre:'SNEAK & RESCUE',color:'#12b69b',bg:'#bdede0',ink:'#0a514b',icon:'⌁',tag:'Quiet paws. A very brave heart.',pitch:'Hide behind crates, rescue toy ducks and reach the exit.',action:'SNEAK',verb:'HOLD TO HIDE / RESCUE',help:'Hold SNEAK to walk quietly and rescue nearby ducks. Bushes hide you while sneaking. Pick up keys for locked cages. Crates block the guards’ sight.',features:['One patrol, two toy ducks','Learn to hide behind crates','Use the mint bushes','A key for a locked cage','Two crossing patrols','Take the long safe route','Rotating security cameras','Three ducks to rescue','The camera switch buys time','Patrols watch the middle lane','An extra locked cage','Three guards, four friends','Hide while a camera turns','The night-shift rescue','The perfect quiet escape']},
 {id:'dino-drift',name:'Dino Drift',animal:'PIP / DINO DRIVER',genre:'DRIFT & RACE',color:'#ffbc24',bg:'#ffebae',ink:'#644314',icon:'↗',tag:'Tiny wheels. Deliciously big corners.',pitch:'Slide through turns, release your drift and ride the turbo.',action:'DRIFT',verb:'HOLD IN TURNS · RELEASE',help:'Steer with the joystick. Hold DRIFT while turning to build power, then release for turbo. Visit the numbered gates in order. The arrow points to the next gate.',features:['A sunny oval warm-up','A rounded square course','The little zigzag','Learn charged drift boosts','A sweeping bean-shaped course','Sandy corners slow your kart','Mint turbo strips','A slippery ice bend','Jump a low candy ramp','A moving gate at the chicane','More tightly placed gates','Ice and sand alternate','A patrol bumper joins the race','A reversed technical course','The grand drift tour']},
 {id:'peach-party',name:'Peach Party',animal:'PEPO / PENGUIN PICKER',genre:'CATCH & DODGE',color:'#eb4c95',bg:'#ffd0e3',ink:'#632d53',icon:'●',tag:'A basket full of very happy surprises.',pitch:'Read the landing rings, catch fruit and dodge the trouble.',action:'CATCH',verb:'HOLD TO OPEN BASKET',help:'Move under landing rings and hold CATCH when fruit lands. Let go to run faster. Dark bombs hurt; golden fruit scores extra. Keep a streak for bonus points.',features:['A gentle peach shower','Golden fruit joins the party','Read the landing rings','Two fruit fall together','Dodge the dark bombs','A second bounce gives another chance','A breeze bends the falling fruit','Cherries arrive in little pairs','Catch the requested fruit color','Icy fruit slows your feet','A timed golden wave','Read wind-bent landing rings','Color requests and double drops','Mix wind, ice and bombs','The fruit-festival finale']}
];
const NAMES=[
 ['First Bento','Rice & Shine','Lunch for Two','Twin Pans','Freshly Chopped','Perfect Timing','Soup Weather','Oops, a Spill','Table for Three','Lunch Break','Rolling Prep','Kitchen Orchestra','Afternoon Rush','Careful Corners','Chef’s Table'],
 ['First Light','Little Zigzag','Around the Hedge','Three Little Turns','A Spare Reflection','Coral or Cyan','Through the Filter','Double Bloom','Secret Garden','Split Sunshine','Open Sesame','Three Wishes','The Dark Side','Color Orchestra','Full Bloom'],
 ['Quiet Paws','Crate Escape','Mint Hideaway','The Brass Key','Crossing Paths','Outside Lane','Watchful Eyes','Three Little Friends','Lights Out','Middle Watch','Lock & Key','Four to Rescue','Wait for the Sweep','Night Shift','Pocket Heroes'],
 ['Sunny Oval','Round the Block','Mini Chicane','First Turbo','Bean Circuit','Sandy Picnic','Mint Express','Ice Cream Bend','Candy Jump','Swinging Gate','Tight Lines','Mixed Grip','Bumper Patrol','Reverse Ribbon','The Drift Cup'],
 ['First Peach','Golden Afternoon','Watch the Rings','Double Delight','Dark Surprise','Second Chance','A Little Breeze','Cherry Twins','Color Please','Icy Feet','Gold Rush','Dancing Drops','Fruit Mixer','Wild Weather','Peach Carnival']
];
export function levelInfo(mode,index){const g=GAMES[mode];return {number:index+1,name:NAMES[mode][index],feature:g.features[index],chapter:index<5?'LEARN':index<10?'MIX':'MASTER'};}
export const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
export const damp=(a,b,k,dt)=>a+(b-a)*(1-Math.exp(-k*dt));
export function rng(seed){let s=seed>>>0;return()=>{s=(Math.imul(s,1664525)+1013904223)>>>0;return s/4294967296;};}
