import {GAMES,levelInfo,clamp} from './catalog.js';
import {Session} from './sim.js';
import {ArcadeView} from './view.js';
import {ToyAudio} from './audio.js';
const $=id=>document.getElementById(id),root=$('app'),params=new URLSearchParams(location.search),base=root.dataset.base||'./',verify=params.get('verify')==='1',still=verify&&params.has('still');
let mode=GAMES.findIndex(g=>g.id===(root.dataset.game||params.get('game'))||location.pathname.split('/').includes(g.id));const isHub=mode<0;mode=Math.max(0,mode);let selected=clamp(Number(params.get('level')||1)-1,0,14),screen=isHub?'hub':'menu',game=new Session(mode,selected),progress={},joy={x:0,z:0},held=false,pendingTap=false,joyId=null,actionId=null,keys=new Set(),last=performance.now(),time=0,uiAge=0,toastUntil=0;
try{const s=JSON.parse(localStorage.getItem('toybox-arcade-v2')||'{}');if(s&&typeof s==='object')progress=s;}catch{}
const audio=new ToyAudio();let view;try{view=new ArcadeView($('scene'));}catch(e){$('failure').hidden=false;throw e;}
$('home').href=base;for(const id of ['back-hub','result-home'])$(id).href='https://github.com/wentaopeng714-cmd/prism-garden';
$('game-cards').innerHTML=GAMES.map((g,i)=>`<a class="game-card" href="https://wentaopeng714-cmd.github.io/${g.id}/" style="--card:${g.color};--card-tint:${g.bg};--card-ink:${g.ink}"><span class="card-symbol"><img src="${base}previews/${g.id}-avatar.png" alt="${g.animal}"></span><span class="card-copy"><small>${String(i+1).padStart(2,'0')} / ${g.genre}</small><strong>${g.name}</strong><span>${g.pitch}</span></span><span class="card-arrow">↗</span></a>`).join('');
function clearInput(){keys.clear();held=false;pendingTap=false;joy={x:0,z:0};joyId=actionId=null;game.lastAction=false;game.charge=0;$('stick').style.transform='translate(0,0)';$('action').classList.remove('held');}
function setScreen(s){screen=s;root.dataset.screen=s;['hub','menu','result'].forEach(id=>$(id).hidden=s!==id);$('hud').hidden=s!=='game';$('controls').hidden=s!=='game';$('pause-panel').hidden=true;$('route-panel').hidden=true;const canvas=$('scene');if(s==='hub')$('hero-preview').append(canvas);else if(s==='menu')$('menu-preview').append(canvas);else root.prepend(canvas);clearInput();view.cameraReady=false;view.resize();}
function load(){game=new Session(mode,selected);view.build(game);const g=GAMES[mode];root.style.setProperty('--accent',g.color);root.style.setProperty('--tint',g.bg);root.style.setProperty('--ink',g.ink);root.style.setProperty('--button-text',mode===1?'#fff9e9':'#243450');$('game-title').textContent=g.name;$('tagline').textContent=g.tag;$('genre').textContent=g.genre;$('animal').textContent=g.animal;$('menu-kicker').textContent=g.genre+' / 15 LITTLE CHALLENGES';$('help').textContent=g.help;$('action-name').textContent=g.action;$('action-icon').textContent=g.icon;$('action-verb').textContent=g.verb;$('move-caption').textContent=mode===3?'STEER':mode===1?'WALK / TAP MIRRORS':'MOVE';$('light').hidden=mode!==1||selected<5;$('gate-switch').hidden=mode!==1||selected<10;document.title=isHub?'Toybox Arcade · Volume 02':g.name+' · Toybox Arcade';}
function menu(){setScreen('menu');load();const info=levelInfo(mode,selected),stars=progress[GAMES[mode].id]?.[selected+1]||0;$('level-number').textContent=String(selected+1).padStart(2,'0')+' / 15';$('chapter').textContent=info.chapter;$('level-title').textContent=info.name;$('level-feature').textContent=info.feature;$('best-stars').textContent=stars?'★'.repeat(stars)+' BEST SO FAR':'A FRESH LITTLE ADVENTURE';$('previous-level').disabled=selected===0;$('following-level').disabled=selected===14;updateUI();}
function start(){audio.wake();setScreen('game');load();updateUI();}
function pause(value){if(screen!=='game'||game.phase==='finished')return;game.paused=value;clearInput();$('pause-panel').hidden=!value;updateUI();}
function toast(s){$('toast').textContent=s;$('toast').classList.add('show');toastUntil=time+2.4;}
function finish(){setScreen('result');if(game.won&&!verify){const id=GAMES[mode].id;progress[id]??={};progress[id][selected+1]=Math.max(progress[id][selected+1]||0,game.stars);try{localStorage.setItem('toybox-arcade-v2',JSON.stringify(progress));}catch{}}$('result-kicker').textContent=game.won?'A LITTLE WIN WORTH CELEBRATING':'TRY A DIFFERENT LITTLE PLAN';$('result-stars').textContent=game.won?'★'.repeat(game.stars):'♡';$('result-title').textContent=game.won?(selected===14?'You mastered this world!':['Chef’s kiss!','Full bloom!','Pocket heroes!','What a sweet drift!','A peach-perfect party!'][mode]):'One more little try?';$('result-detail').textContent=game.won?`${game.level.name} · ${Math.ceil(game.remaining)}s left · ${game.mistakes} mishaps`:game.reason;$('next').textContent=game.won&&selected<14?'NEXT CHALLENGE ↗':'TRY AGAIN ↻';updateUI();}
function handle(e){view.event(e);audio.play(['rescue','gate','ready','pick','turn'].includes(e.type)?'collect':e.type==='boost'?'jump':e.type);if(e.message)toast(e.message);if(e.type==='win'||e.type==='lose')finish();}
function gardenTouch(kind,id=0){if(mode!==1||screen!=='game'||game.paused)return;game.touch(kind,id);for(const e of game.events)handle(e);game.events=[];updateUI();}
function updateUI(){const h=game.hud(),sec=Math.ceil(game.remaining);$('hud-game').textContent=GAMES[mode].name.toUpperCase();$('goal').textContent=h.goal;$('timer').textContent=Math.floor(sec/60)+':'+String(sec%60).padStart(2,'0');$('timer').parentElement.classList.toggle('urgent',sec<=10);$('hud-level').textContent=String(selected+1).padStart(2,'0')+' / '+game.level.name;$('lives').textContent=h.lives?'♥'.repeat(Math.max(0,h.lives)):'';$('goal-progress').style.width=clamp(game.score/game.total)*100+'%';$('hint').textContent=h.hint;$('status').textContent=h.meter;if(mode===0){const near=game.near;let label='INTERACT';if(near?.kind==='bin'&&!game.hand)label='TAKE';if(near?.kind==='stove')label=game.hand&&!game.hand.ready?'COOK':!game.hand&&game.stoves[near.id].job?.ready?'PICK UP':'INTERACT';if(near?.kind==='prep'&&game.hand&&!game.hand.chopped)label='CHOP';if(near?.kind==='guest'&&game.hand?.ready)label='SERVE';if(near?.kind==='trash'&&game.hand)label='CLEAR';$('action-name').textContent=label;}$('status-fill').style.width=clamp(h.fill)*100+'%';$('action').style.setProperty('--power',clamp(game.charge)*100+'%');$('action').classList.toggle('held',held||keys.has(' '));$('countdown').hidden=screen!=='game'||game.phase!=='countdown';$('countdown-number').textContent=game.countdown>.35?String(Math.ceil(game.countdown)):'GO!';const colors={coral:'#ff694b',mint:'#16ba9e',yellow:'#edaf23',blue:'#377fe8'};const tickets=h.extra.map(q=>`<div class="ticket" style="--ticket:${colors[q.color]}">${q.label}<i><b style="width:${q.value*100}%"></b></i></div>`).join('');if($('tickets').innerHTML!==tickets)$('tickets').innerHTML=tickets;if(mode===1)$('light').style.background=game.light===1?'#ffb29f':'#b1d0ff';if(verify)root.dataset.qa=JSON.stringify({mode,level:selected+1,screen,phase:game.phase,paused:game.paused,held,joy,charge:game.charge,x:game.player.x,z:game.player.z,score:game.score,total:game.total,remaining:game.remaining,moves:game.moves,drawCalls:view.renderer.info.render.calls});}
function routes(){const wins=progress[GAMES[mode].id]||{};$('completion').textContent=Object.keys(wins).length+' / 15 cleared';$('level-grid').innerHTML=Array.from({length:15},(_,i)=>{const q=levelInfo(mode,i);return `<button data-level="${i}" class="${i===selected?'selected':''}" aria-label="Level ${i+1}: ${q.name}" aria-pressed="${i===selected}"><b>${String(i+1).padStart(2,'0')}</b><small>${wins[i+1]?'★'.repeat(wins[i+1]):q.chapter}</small></button>`;}).join('');$('route-panel').hidden=false;}
$('start').onclick=start;$('retry').onclick=start;$('pause').onclick=()=>pause(!game.paused);$('resume').onclick=()=>pause(false);$('pause-retry').onclick=start;$('pause-menu').onclick=menu;$('result-menu').onclick=menu;$('next').onclick=()=>{if(game.won&&selected<14)selected++;start();};$('choose-level').onclick=routes;$('close-routes').onclick=()=>{$('route-panel').hidden=true;};$('previous-level').onclick=()=>{selected=Math.max(0,selected-1);menu();};$('following-level').onclick=()=>{selected=Math.min(14,selected+1);menu();};$('level-grid').onclick=e=>{const b=e.target.closest('[data-level]');if(!b)return;selected=Number(b.dataset.level);menu();};$('sound').onclick=()=>{audio.wake();const on=audio.toggle();$('sound').textContent=on?'♪':'♫̸';$('sound').setAttribute('aria-label',on?'Mute sound':'Enable sound');$('sound').setAttribute('aria-pressed',String(on));};$('light').onclick=()=>gardenTouch('source');$('gate-switch').onclick=()=>gardenTouch('switch');
function stick(e){const r=$('joystick').getBoundingClientRect(),x=e.clientX-r.left-r.width/2,z=e.clientY-r.top-r.height/2,radius=r.width*.29,n=Math.max(radius,Math.hypot(x,z));joy={x:x/n,z:z/n};if(Math.hypot(joy.x,joy.z)<.06)joy={x:0,z:0};$('stick').style.transform=`translate(${joy.x*radius}px,${joy.z*radius}px)`;}
$('joystick').addEventListener('pointerdown',e=>{if(joyId!==null)return;e.preventDefault();joyId=e.pointerId;$('joystick').setPointerCapture(e.pointerId);stick(e);});$('joystick').addEventListener('pointermove',e=>{if(joyId===e.pointerId)stick(e);});const releaseJoy=e=>{if(joyId!==e.pointerId)return;joyId=null;joy={x:0,z:0};$('stick').style.transform='translate(0,0)';};for(const name of ['pointerup','pointercancel','lostpointercapture'])$('joystick').addEventListener(name,releaseJoy);
$('action').addEventListener('pointerdown',e=>{if(actionId!==null)return;e.preventDefault();audio.wake();held=true;if((mode===0||mode===1)&&game.phase==='play')pendingTap=true;actionId=e.pointerId;$('action').setPointerCapture(e.pointerId);});const releaseAction=e=>{if(actionId!==e.pointerId)return;held=false;actionId=null;if(e.type==='pointercancel'){pendingTap=false;game.charge=0;game.lastAction=false;}};for(const name of ['pointerup','pointercancel','lostpointercapture'])$('action').addEventListener(name,releaseAction);
$('scene').addEventListener('pointerdown',e=>{if(mode!==1||screen!=='game'||game.phase!=='play'||game.paused)return;const hit=view.pick(e.clientX,e.clientY);if(hit){audio.wake();gardenTouch(hit.kind,hit.id);}});
window.addEventListener('keydown',e=>{if(screen!=='game')return;const k=e.key.toLowerCase();if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();if(k==='escape')pause(!game.paused);if(k===' '&&!e.repeat&&(mode===0||mode===1)&&game.phase==='play')pendingTap=true;if(!e.repeat&&k==='c')gardenTouch('source');if(!e.repeat&&k==='g')gardenTouch('switch');if(!e.repeat&&/^[1-9]$/.test(k))gardenTouch('mirror',Number(k)-1);keys.add(k);});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{if(screen==='game')pause(true);else clearInput();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&screen==='game')pause(true);});
function frame(now){requestAnimationFrame(frame);const dt=Math.min(.075,(now-last)/1000);last=now;const frozen=game.paused||document.hidden,visualDt=frozen?0:dt;time+=visualDt;if(screen==='game'&&!frozen&&!still){const input={x:joy.x+(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),z:joy.z+(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0),action:held||keys.has(' ')||pendingTap};pendingTap=false;let left=dt;while(left>1e-7&&screen==='game'){const step=Math.min(left,1/90);game.update(step,input);for(const e of game.events)handle(e);left-=step;}}view.update(game,visualDt,time,screen);uiAge+=dt;if(uiAge>.10){updateUI();uiAge=0;}if(toastUntil&&time>toastUntil){$('toast').classList.remove('show');toastUntil=0;}}
load();if(isHub){setScreen('hub');updateUI();}else menu();if(verify&&params.has('demo')&&!isHub){setScreen('game');load();game.phase='play';if(params.get('demo')==='action'){if(mode===0){game.hand={recipe:{name:'GREENS',color:'mint'},ready:true};game.stoves[0].job={recipe:{name:'RICE',color:'coral',cook:2.5},age:2,ready:false};}if(mode===1){game.garden.mirrors.forEach(q=>{if(q.solution!==null)q.state=q.solution;});game.light=game.garden.sourceColor;game.shutterOpen=true;game.gardenUpdate(0,{x:0,z:0},false);}if(mode===2){game.player.x=-4;game.player.z=-2.2;held=true;game.action=true;}if(mode===3){game.player.vx=3;game.player.vz=-2;game.boost=1;game.charge=.7;held=true;}if(mode===4){held=true;game.action=true;game.spawnFruit();game.spawnFruit();}}if(['win','loss'].includes(params.get('demo'))){game.finish(params.get('demo')==='win','A fresh plan is one tap away.');finish();}updateUI();}if(verify&&params.has('portrait')){root.dataset.portrait='true';root.prepend($('scene'));view.resize();view.cameraReady=false;}requestAnimationFrame(frame);window.addEventListener('error',()=>{$('failure').hidden=false;});
