import {clamp,damp,rng,levelInfo} from './catalog.js';
export {clamp,damp};
export const distance=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);
export function segmentBlocked(a,b,boxes){return boxes.some(q=>{let lo=0,hi=1;for(const axis of ['x','z']){const d=b[axis]-a[axis],min=q[axis]-q[axis==='x'?'w':'d']/2,max=q[axis]+q[axis==='x'?'w':'d']/2;if(Math.abs(d)<1e-8){if(a[axis]<min||a[axis]>max)return false;}else{let t0=(min-a[axis])/d,t1=(max-a[axis])/d;if(t0>t1)[t0,t1]=[t1,t0];lo=Math.max(lo,t0);hi=Math.min(hi,t1);if(lo>hi)return false;}}return hi>.01&&lo<.99;});}
export function moveBody(p,dt,input,speed,boxes=[],bounds={x:6,z:7},grip=12){const n=Math.max(1,Math.hypot(input.x,input.z));p.vx=damp(p.vx,input.x/n*speed,grip,dt);p.vz=damp(p.vz,input.z/n*speed,grip,dt);for(const axis of ['x','z']){p[axis]+=p[axis==='x'?'vx':'vz']*dt;p[axis]=clamp(p[axis],-bounds[axis]+.4,bounds[axis]-.4);for(const b of boxes){const hx=b.w/2+.34,hz=b.d/2+.34;if(Math.abs(p.x-b.x)<hx&&Math.abs(p.z-b.z)<hz){const delta=p[axis]-b[axis];p[axis]=b[axis]+(delta>=0?1:-1)*(axis==='x'?hx:hz);p[axis==='x'?'vx':'vz']=0;}}}const v=Math.hypot(p.vx,p.vz);p.walk+=v*dt;if(v>.1){const target=Math.atan2(p.vx,p.vz);let d=(target-p.angle+Math.PI*3)%(Math.PI*2)-Math.PI;p.turn=d;p.angle+=d*(1-Math.exp(-12*dt));}else p.turn=damp(p.turn,0,12,dt);}

const RECIPES=[{name:'RICE',type:0,cooker:0,cook:2.5,color:'coral'},{name:'GREENS',type:1,cooker:0,cook:3.2,color:'mint'},{name:'NOODLES',type:2,cooker:1,cook:3.7,color:'yellow'},{name:'SOUP',type:0,cooker:2,cook:4.2,color:'blue'}];
export function recipe(type,level){const r={...RECIPES[type]};r.chop=level>=4&&type===1;r.cook+=level>=11?.5:0;return r;}
export function kitchenLayout(index){return {bins:[{id:0,x:-4.5,z:-4.3},{id:1,x:-1.5,z:-4.3},{id:2,x:1.5,z:-4.3}],prep:{x:4.5,z:-4.3},stoves:[{id:0,x:-3.5,z:-.5,w:1.8,d:1.3},{id:1,x:0,z:-.5,w:1.8,d:1.3},{id:2,x:3.5,z:-.5,w:1.8,d:1.3}],customers:[{x:-4,z:4.4},{x:0,z:4.4},{x:4,z:4.4}],trash:{x:5.5,z:2.4}};}

const DIRS=[{x:1,z:0},{x:0,z:1},{x:-1,z:0},{x:0,z:-1}],REFLECT=[[3,2,1,0],[1,0,3,2]];
export function gardenSpec(index){const count=2+Math.floor(index/3),a=2+index%2,b=5+index%2,row=4-Math.floor(index/2)%2,top=1+index%2,end= index%2;const turns=[{x:a,z:6,out:3},{x:a,z:row,out:0},{x:b,z:row,out:3},{x:b,z:top,out:2},{x:end,z:top,out:3},{x:end,z:0,out:0}].slice(0,count);let incoming=0;const mirrors=turns.map((q,id)=>{const solution=REFLECT.findIndex(r=>r[incoming]===q.out);incoming=q.out;return {...q,id,solution,state:solution^1,blocked:index>=12&&id%2===0};});const last=turns.at(-1),d=DIRS[last.out],goal={x:last.x+d.x*(last.out===3?1:2),z:last.z+d.z*(last.out===3?1:2)};goal.x=clamp(goal.x,0,6);goal.z=clamp(goal.z,0,6);const cells=[];let p={x:-1,z:6},direction=0;for(let t=0;t<60;t++){p={x:p.x+DIRS[direction].x,z:p.z+DIRS[direction].z};cells.push({...p});const m=mirrors.find(q=>q.x===p.x&&q.z===p.z);if(m)direction=m.out;if(p.x===goal.x&&p.z===goal.z)break;}
 const filter=index>=6?cells.find((q,j)=>j>3&&!mirrors.some(m=>m.x===q.x&&m.z===q.z)&&q.z!==6&&!(q.x===goal.x&&q.z===goal.z)):null;const sourceColor=index>=5?(index%2?2:1):1,goals=[{...goal,color:filter?4:sourceColor,id:0}];if(index>=7){const q=cells.find((q,j)=>j>3&&!mirrors.some(m=>m.x===q.x&&m.z===q.z)&&q.z>goal.z);if(q)goals.push({...q,color:filter&&cells.indexOf(q)>=cells.indexOf(filter)?4:sourceColor,id:1});}if(index>=9)goals.push({x:1,z:5,color:sourceColor,id:goals.length});
 const used=new Set(cells.map(q=>`${q.x},${q.z}`));const extras=index>=4?[{x:6,z:6,id:mirrors.length,state:index%2,solution:null,blocked:false}].filter(q=>!used.has(`${q.x},${q.z}`)):[];
 return {mirrors:[...mirrors,...extras],goals,cells,sourceColor,filter:filter?{...filter,color:4}:null,splitter:index>=9?{x:1,z:6}:null,shutter:index>=10?{...cells.find((q,j)=>j>4&&!mirrors.some(m=>m.x===q.x&&m.z===q.z)&&(!filter||q.x!==filter.x||q.z!==filter.z))}:null};}
export function traceGarden(m){const jobs=[{x:-1,z:6,d:0,color:m.light}],segments=[],lit=new Set(),visited=new Set();while(jobs.length&&segments.length<120){const p=jobs.shift();const d=DIRS[p.d],next={x:p.x+d.x,z:p.z+d.z};if(next.x<0||next.x>6||next.z<0||next.z>6)continue;const key=`${next.x},${next.z},${p.d},${p.color}`;if(visited.has(key))continue;visited.add(key);segments.push({a:{x:p.x,z:p.z},b:next,color:p.color});let color=p.color,direction=p.d;if(m.garden.shutter&&!m.shutterOpen&&next.x===m.garden.shutter.x&&next.z===m.garden.shutter.z)continue;if(m.garden.filter&&next.x===m.garden.filter.x&&next.z===m.garden.filter.z)color=m.garden.filter.color;for(const g of m.garden.goals)if(g.x===next.x&&g.z===next.z&&g.color===color)lit.add(g.id);const mirror=m.garden.mirrors.find(q=>q.x===next.x&&q.z===next.z);if(mirror){if(mirror.state===2)continue;direction=REFLECT[mirror.state][direction];}if(m.garden.splitter&&next.x===1&&next.z===6)jobs.push({...next,d:3,color});jobs.push({...next,d:direction,color});}return {segments,lit};}
export const gardenPoint=q=>({x:(q.x-3)*1.4,z:(q.z-3)*1.4});

const COURSES=[[[0,6],[-4.5,4.2],[-5.5,0],[-4,-5],[0,-6],[4,-4.5],[5.5,0],[4.5,4.2]],[[0,6],[-4.8,6],[-5.6,2],[-5.6,-4],[-3,-6],[3,-6],[5.6,-3],[5.6,3],[4,6]],[[0,6],[-4.8,4],[-1.2,1.6],[-5,-1.4],[-4,-5],[0,-6],[4,-4],[1.4,-1],[5,2],[4,5]],[[0,6],[-4.3,4.5],[-5.7,0],[-4,-4.5],[0,-5.8],[4,-4.3],[5,0],[2.5,2],[4.5,4.5]],[[0,6],[-5,5],[-4,1.2],[-5,-3],[0,-5.8],[4,-4],[5,0],[2,1.5],[5,4.8]]];
export function courseSpec(index){let path=COURSES[index%5].map(([x,z])=>({x,z}));if(index>=13)path=[path[0],...path.slice(1).reverse()];if(index>=10){const result=[];path.forEach((q,j)=>{result.push(q);if(j===2||j===5){const n=path[(j+1)%path.length];result.push({x:(q.x+n.x)/2,z:(q.z+n.z)/2});}});path=result;}const length=path.reduce((sum,q,j)=>sum+distance(q,path[(j+1)%path.length]),0);return {gates:[...path.slice(1),path[0]].map((q,id)=>({...q,id})),start:path[0],length};}

export class Session{
 constructor(mode,index){this.mode=mode;this.index=index;this.level=levelInfo(mode,index);this.rand=rng(1500+mode*173+index*73);this.phase='countdown';this.countdown=2.4;this.time=0;this.paused=false;this.events=[];this.won=false;this.mistakes=0;this.score=0;this.lastAction=false;this.action=false;this.charge=0;this.cooldown=0;this.player={x:0,z:3,y:0,vx:0,vz:0,angle:0,turn:0,walk:0};this.bounds={x:6.5,z:7};this.boxes=[];this.total=1;this.budget=90;
  if(mode===0)this.makeKitchen();if(mode===1)this.makeGarden();if(mode===2)this.makeHeist();if(mode===3)this.makeRace();if(mode===4)this.makeParty();this.remaining=this.budget;
 }
 emit(type,x=this.player.x,z=this.player.z,message=''){this.events.push({type,x,z,message});}
 finish(won,reason=''){if(this.phase==='finished')return;this.phase='finished';this.won=won;this.reason=reason;this.stars=won?1+(this.mistakes===0?1:0)+(this.remaining>this.budget*.22&&(this.mode!==1||this.moves<=this.par+2)?1:0):0;this.emit(won?'win':'lose');}
 update(dt,input={x:0,z:0,action:false}){this.events=[];if(this.paused||this.phase==='finished')return;if(this.phase==='countdown'){this.countdown-=dt;if(this.countdown<=0){this.phase='play';this.emit('go');}return;}this.time+=dt;this.remaining=Math.max(0,this.remaining-dt);this.cooldown=Math.max(0,this.cooldown-dt);this.action=!!input.action;const pressed=this.action&&!this.lastAction;if(this.mode===0)this.kitchen(dt,input,pressed);if(this.mode===1)this.gardenUpdate(dt,input,pressed);if(this.mode===2)this.heist(dt,input);if(this.mode===3)this.race(dt,input);if(this.mode===4)this.party(dt,input);this.lastAction=this.action;if(this.remaining<=0&&this.phase!=='finished')this.finish(false,'The clock ran out. Try a new route or a different plan.');}
 makeKitchen(){this.layout=kitchenLayout(this.index);this.player.z=2.2;this.bounds={x:7,z:6.4};this.total=4+Math.floor(this.index/3);this.budget=100+this.index*5;this.hand=null;this.prep=0;this.stoves=this.layout.stoves.map(q=>({...q,job:null}));this.boxes=[...this.stoves,...this.layout.bins.map(q=>({...q,w:1.7,d:1.1})),{...this.layout.prep,w:1.8,d:1.2}];this.orderTypes=Array.from({length:this.total},(_,j)=>this.index<1?0:this.index<3?(j+this.index)%2:this.index<6?(j+this.index)%3:(j+this.index)%4);this.orders=this.orderTypes.map((type,id)=>({id,type,done:false,patience:43-Math.min(12,this.index)*.55,active:false}));this.fillOrders();this.spills=this.index>=7?[{x:2,z:2,r:1},{x:-4.5,z:1.2,r:.75}].slice(0,this.index>=13?2:1):[];}
 fillOrders(){const n=this.index<2?1:this.index<8?2:3;let active=this.orders.filter(q=>q.active&&!q.done).length;for(const q of this.orders)if(!q.done&&!q.active&&active<n){q.active=true;q.patience=43-Math.min(12,this.index)*.55;active++;}}
 nearbyKitchen(){const p=this.player,items=[...this.layout.bins.map(q=>({...q,kind:'bin'})),...this.stoves.map(q=>({...q,kind:'stove'})),{...this.layout.prep,kind:'prep'},{...this.layout.trash,kind:'trash'},...this.orders.filter(q=>q.active&&!q.done).map((q,j)=>({...this.layout.customers[j],id:q.id,kind:'guest'}))];return items.sort((a,b)=>distance(p,a)-distance(p,b)).find(q=>distance(p,q)<1.65)||null;}
 kitchen(dt,input,pressed){if(this.index>=10){this.layout.prep.x=4.5+Math.sin(this.time*.6)*.55;this.boxes.at(-1).x=this.layout.prep.x;}const slow=this.spills.some(q=>distance(q,this.player)<q.r);moveBody(this.player,dt,input,slow?2.5:4.5,this.boxes,this.bounds);for(const s of this.stoves)if(s.job){s.job.age+=dt;if(!s.job.ready&&s.job.age>=s.job.recipe.cook){s.job.ready=true;s.job.age=0;this.emit('ready',s.x,s.z,'Dish ready! Pick it up before it burns.');}else if(s.job.ready&&s.job.age>(this.index<5?18:13)){s.job=null;this.mistakes++;this.emit('hit',s.x,s.z,'Oops, overcooked. A fresh ingredient will help.');}}for(const q of this.orders)if(q.active&&!q.done){q.patience-=dt;if(q.patience<=0){this.mistakes++;q.patience=38;this.emit('hit',0,4.4,'A guest lost patience. Their order is still available.');if(this.mistakes>=4)this.finish(false,'Four kitchen mishaps. Try cooking two dishes at the same time.');}}
 const near=this.nearbyKitchen();this.near=near;if(near?.kind==='prep'&&this.hand&&!this.hand.ready&&this.hand.recipe.chop&&!this.hand.chopped&&this.action){this.prep+=dt;if(this.prep>=1.4){this.hand.chopped=true;this.prep=0;this.emit('collect',near.x,near.z,'Freshly chopped. Now take it to the pan.');}}else this.prep=Math.max(0,this.prep-dt*.5);if(!pressed||!near||this.cooldown>0)return;this.cooldown=.25;
 if(near.kind==='bin'&&!this.hand){const pending=this.orders.find(q=>q.active&&!q.done&&recipe(q.type,this.index).type===near.id&&!this.stoves.some(s=>s.job?.recipe.name===recipe(q.type,this.index).name));const r=recipe(pending?.type??near.id,this.index);this.hand={recipe:r,ready:false,chopped:!r.chop};this.emit('pick');}
 if(near.kind==='stove'){const s=this.stoves[near.id];if(!this.hand&&s.job?.ready){this.hand={recipe:s.job.recipe,ready:true,chopped:true};s.job=null;this.emit('pick');}else if(this.hand&&!this.hand.ready&&!s.job){if(!this.hand.chopped)this.emit('notice',near.x,near.z,'Chop this ingredient at PREP first.');else if(this.hand.recipe.cooker!==s.id)this.emit('notice',near.x,near.z,'Use '+['PAN','NOODLES','SOUP'][this.hand.recipe.cooker]+'.');else{s.job={recipe:this.hand.recipe,age:0,ready:false};this.hand=null;this.emit('cook',s.x,s.z);}}}
 if(near.kind==='guest'&&this.hand?.ready){const q=this.orders[near.id];if(RECIPES[q.type].name===this.hand.recipe.name){q.done=true;q.active=false;this.hand=null;this.score++;this.fillOrders();this.emit('collect',near.x,near.z,'One happy guest!');if(this.score>=this.total)this.finish(true);}else this.emit('notice',near.x,near.z,'This guest ordered '+RECIPES[q.type].name+'.');}if(near.kind==='trash'&&this.hand){this.hand=null;this.emit('notice',near.x,near.z,'Hands free. Make a fresh dish.');}}
 makeGarden(){this.garden=gardenSpec(this.index);this.total=this.garden.goals.length;this.budget=180-this.index*2;this.player={...this.player,x:-5.3,z:4.2};this.bounds={x:6.2,z:6.2};this.light=this.index>=5?(this.garden.sourceColor===1?2:1):1;this.shutterOpen=!this.garden.shutter;this.moves=0;this.par=this.garden.mirrors.filter(q=>q.solution!==null).reduce((sum,q)=>sum+(q.solution-q.state+(q.blocked?3:2))%(q.blocked?3:2),0)+(this.index>=5?1:0)+(this.garden.shutter?1:0);this.bloom=0;this.selected=this.garden.mirrors[0].id;this.trace=traceGarden(this);}
 touch(kind,id){if(this.phase!=='play'||this.paused||this.mode!==1)return;if(kind==='mirror'){const q=this.garden.mirrors.find(q=>q.id===id);if(!q)return;q.state=(q.state+1)%(q.blocked?3:2);this.selected=id;this.autoTarget=gardenPoint(q);this.moves++;this.emit('turn',this.autoTarget.x,this.autoTarget.z);}if(kind==='source'){this.light=this.light===1?2:1;this.moves++;this.emit('turn',-5,4.2);}if(kind==='switch'){this.shutterOpen=!this.shutterOpen;this.moves++;this.emit('turn',5.3,4.3);}this.trace=traceGarden(this);}
 gardenUpdate(dt,input,pressed){if(pressed)this.touch('mirror',this.selected);let move=input;if(Math.hypot(input.x,input.z)<.1&&this.autoTarget){const d=distance(this.player,this.autoTarget);move=d>.55?{x:(this.autoTarget.x-this.player.x)/d,z:(this.autoTarget.z-this.player.z)/d}:{x:0,z:0};}else if(Math.hypot(input.x,input.z)>.1)this.autoTarget=null;moveBody(this.player,dt,move,3.2,[],this.bounds);this.trace=traceGarden(this);this.score=this.trace.lit.size;this.bloom=this.score===this.total?this.bloom+dt:0;if(this.bloom>1.1)this.finish(true);}
 makeHeist(){this.bounds={x:7,z:8.5};this.budget=115+this.index*5;this.player.z=6.5;this.total=2+Math.floor(this.index/5);this.cages=[{x:-4.7,z:-6},{x:4.7,z:-6},{x:-4.7,z:1.3},{x:4.7,z:1.3}].slice(0,this.total).map((q,id)=>({...q,id,freed:false,progress:0,locked:this.index>=3&&(id===1||this.index>=10&&id===3)}));this.key={x:5.6,z:5.8,taken:false};this.exit={x:0,z:-7.5};this.switch={x:-5.7,z:5.6};this.off=0;this.alarm=0;this.strikes=0;this.invulnerable=0;this.bushes=[{x:-5.4,z:-1.8,r:1.1},{x:5.4,z:-1.8,r:1.1},{x:0,z:4.4,r:1.05},...[-1,1].flatMap(side=>[-3.8,2.8,...(this.index>=10?[-.1]:[])].map(z=>({x:side*5.6,z,r:1.05})))];const shift=this.index%3*.45;this.boxes=[{x:-2.2,z:-2.5,w:2.0,d:1.6},{x:2.2,z:-2.5,w:2.0,d:1.6},{x:0,z:1.1+shift,w:2.3,d:1.7}];if(this.index>=5)this.boxes.push({x:0,z:-5.4,w:2,d:1.1});this.guards=Array.from({length:1+Math.floor(this.index/5)},(_,id)=>({id,x:0,z:id===0?-3.8:id===1?2.8:-.1,angle:0,range:4.8,speed:.36+this.index*.016,phase:id*Math.PI*.7}));this.cameras=this.index>=6?Array.from({length:this.index>=11?2:1},(_,id)=>({id,x:id?5.8:-5.8,z:-5.8,angle:0,range:6.1})):[];this.coins=[{x:-5.7,z:3.4,taken:false},{x:5.7,z:-3.5,taken:false},{x:0,z:-6.9,taken:false}];this.coinsTaken=0;this.cagePanels=this.cages.map(c=>({x:c.x+Math.sign(c.x)*.82,z:c.z,w:.16,d:1.5}));this.boxes.push(...this.cagePanels);}
 visibleBy(g){const p=this.player,d=distance(p,g);if(d>(this.action&&this.guards.includes(g)?3.3:g.range))return false;const dot=(Math.sin(g.angle)*(p.x-g.x)+Math.cos(g.angle)*(p.z-g.z))/Math.max(.01,d);return dot>.69&&!segmentBlocked(g,p,this.boxes);}
 heist(dt,input){moveBody(this.player,dt,input,this.action?2.8:4.7,this.boxes,this.bounds);this.invulnerable=Math.max(0,this.invulnerable-dt);this.off=Math.max(0,this.off-dt);this.hidden=this.action&&this.bushes.some(q=>distance(q,this.player)<q.r);for(const g of this.guards){g.x=Math.sin(this.time*g.speed+g.phase)*4.2;const target=Math.cos(this.time*g.speed+g.phase)>0?Math.PI/2:-Math.PI/2;g.angle=damp(g.angle,target,8,dt);}for(const c of this.cameras)c.angle=(c.x<0?Math.PI/2:-Math.PI/2)+Math.sin(this.time*.75+c.id)*.75;this.seen=!this.hidden&&[...this.guards,...(this.off>0?[]:this.cameras)].some(g=>this.visibleBy(g));this.alarm=clamp(this.alarm+dt*(this.seen&&this.invulnerable<=0?1.1:-.75));if(this.alarm>=1&&this.invulnerable<=0){this.strikes++;this.mistakes++;this.player.x=0;this.player.z=6.5;this.player.vx=this.player.vz=0;this.alarm=0;this.invulnerable=2;this.emit('hit',0,6.5,'Spotted! Rescued friends stay safe.');if(this.strikes>=3)this.finish(false,'Three alarms. Try bushes, crates and the camera switch.');}if(this.index>=3&&!this.key.taken&&distance(this.player,this.key)<.8){this.key.taken=true;this.emit('collect',this.key.x,this.key.z,'Brass key collected.');}for(const c of this.coins)if(!c.taken&&distance(this.player,c)<.65){c.taken=true;this.coinsTaken++;this.emit('collect',c.x,c.z);}for(const c of this.cages)if(!c.freed&&distance(this.player,c)<1.3&&this.action){if(c.locked&&!this.key.taken){if(this.cooldown<=0){this.emit('notice',c.x,c.z,'Find the brass key for this lock.');this.cooldown=2;}}else{c.progress+=dt;if(c.progress>=.9){c.freed=true;this.score++;this.emit('rescue',c.x,c.z,'A little friend is safe!');}}}if(this.index>=8&&this.action&&distance(this.player,this.switch)<1.2&&this.off<.5){this.off=14;this.emit('switch',this.switch.x,this.switch.z,'Cameras asleep for 14 seconds.');}if(this.score>=this.total&&distance(this.player,this.exit)<1.0)this.finish(true);}
 makeRace(){this.course=courseSpec(this.index);this.player.x=this.course.start.x;this.player.z=this.course.start.z;this.player.angle=Math.atan2(this.course.gates[0].x-this.player.x,this.course.gates[0].z-this.player.z);this.bounds={x:7.1,z:8.2};this.total=this.course.gates.length;this.budget=Math.ceil(this.course.length/4.5*2+15);this.boost=0;this.invulnerable=0;this.surface='road';this.surfaces=[];if(this.index>=5)this.surfaces.push({x:-4.8,z:1.0,r:1.65,kind:'sand'});if(this.index>=7)this.surfaces.push({x:4,z:-3.5,r:1.65,kind:'ice'});if(this.index>=11)this.surfaces.push({x:-3.5,z:-4.3,r:1.3,kind:'ice'});this.pads=this.index>=6?[{x:0,z:-5.7,kind:'boost'},{x:4.6,z:3.5,kind:this.index>=8?'ramp':'boost'}]:[];this.air=0;this.bumper=this.index>=12?{x:0,z:0,r:.7}:null;this.padsCooldown=0;this.boxes=[{x:0,z:-.3,w:1.4,d:1.4}];this.swing=this.index>=9?{...this.course.gates[3],angle:0,r:1.1}:null;}
 race(dt,input){const p=this.player,speed=Math.hypot(p.vx,p.vz),want=Math.atan2(input.x,input.z);const turning=Math.abs((want-p.angle+Math.PI*3)%(Math.PI*2)-Math.PI);this.invulnerable=Math.max(0,this.invulnerable-dt);this.boost=Math.max(0,this.boost-dt);this.air=Math.max(0,this.air-dt);this.padsCooldown=Math.max(0,this.padsCooldown-dt);this.surface=this.surfaces.find(q=>distance(p,q)<q.r)?.kind||'road';if(this.action&&speed>1.3&&Math.hypot(input.x,input.z)>.2&&turning>.10)this.charge=clamp(this.charge+dt*.55);if(!this.action&&this.lastAction){if(this.charge>.15){this.boost=.5+this.charge*1.8;this.emit('boost');}this.charge=0;}const maximum=this.boost>0?8.2:this.surface==='sand'?3.0:5.2,grip=this.surface==='ice'?2.4:this.action?3.3:8;moveBody(p,dt,input,maximum,this.boxes,this.bounds,grip);p.y=this.air>0?Math.sin(this.air/.85*Math.PI)*.65:0;for(const pad of this.pads)if(distance(p,pad)<.95&&this.padsCooldown<=0){this.padsCooldown=1.3;if(pad.kind==='ramp'){this.air=.85;this.emit('jump');}else{this.boost=1.3;this.emit('boost');}}const gate=this.course.gates[this.score];if(gate&&distance(p,gate)<1.4){this.score++;this.emit('gate',gate.x,gate.z);if(this.score>=this.total)this.finish(true);}if(this.swing){this.swing.angle=Math.sin(this.time*1.15)*.9;const g=this.swing,dx=p.x-g.x,dz=p.z-g.z,u=dx*Math.cos(g.angle)+dz*Math.sin(g.angle),v=-dx*Math.sin(g.angle)+dz*Math.cos(g.angle);if(Math.abs(u)<g.r+.3&&Math.abs(v)<.36&&this.air<=0&&this.invulnerable<=0){this.invulnerable=1.3;this.mistakes++;this.remaining=Math.max(0,this.remaining-1.5);p.vx*=-.35;p.vz*=-.35;this.emit('hit',p.x,p.z,'Swinging gate! Slip around its end.');}}if(this.bumper){this.bumper.x=Math.sin(this.time*.9)*4.8;this.bumper.z=2.2;if(distance(p,this.bumper)<1.05&&this.air<=0&&this.invulnerable<=0){this.invulnerable=1.5;this.mistakes++;this.remaining=Math.max(0,this.remaining-3);p.vx*=-.7;p.vz*=-.7;this.emit('hit',p.x,p.z,'Bumper! Three seconds off the clock.');}}}
 makeParty(){this.bounds={x:5.2,z:5.2};this.player.z=1.3;this.budget=70;this.total=10+this.index;this.fruit=[];this.spawn=.65;this.fruitId=0;this.combo=0;this.bestCombo=0;this.hearts=3;this.slow=0;this.invulnerable=0;this.request=this.index>=8?0:null;this.requestCount=0;this.wind=this.index>=6?Math.sin(this.index*1.3)*.7:0;this.wave=0;}
 spawnFruit(){const id=this.fruitId++,r=this.rand(),bomb=this.index>=4&&id%6===5,kind=this.index>=10&&((this.time>=20&&this.time<25)||(this.time>=45&&this.time<50))?'gold':bomb?'bomb':this.index>=9&&id%9===7?'ice':id%5===3&&this.index>=1?'gold':this.index>=7&&id%7===4?'cherry':'fruit';const type=id%2,x=(this.rand()-.5)*7,z=(this.rand()-.5)*6.8;this.fruit.push({id,x,z,startX:x,startZ:z,y:7,age:0,duration:3.4-Math.min(14,this.index)*.045,kind,type,done:false,bounced:false});if(this.index>=3&&id%4===0)this.fruit.push({id:this.fruitId++,x:clamp(x+1,-3.8,3.8),z:z+.35,startX:clamp(x+1,-3.8,3.8),startZ:z+.35,y:7,age:-.2,duration:3.3,kind:'fruit',type,done:false,bounced:false});}
 party(dt,input){this.slow=Math.max(0,this.slow-dt);this.invulnerable=Math.max(0,this.invulnerable-dt);moveBody(this.player,dt,input,this.slow>0?2.1:this.action?3.2:5.0,[],this.bounds);this.spawn-=dt;if(this.spawn<=0){this.spawnFruit();this.spawn=2.15-Math.min(14,this.index)*.075;}for(const f of this.fruit)if(!f.done){f.age+=dt;f.x=clamp(f.startX+this.wind*Math.sin(Math.max(0,f.age)/f.duration*Math.PI/2),-4.1,4.1);f.y=(f.bounced?2:7)*(1-clamp(f.age/f.duration)**2);if(f.age<f.duration)continue;const close=distance(f,this.player)<(this.action?1.15:.55);if(f.kind==='bomb'){f.done=true;if(close&&this.invulnerable<=0){this.hearts--;this.mistakes++;this.combo=0;this.invulnerable=1.1;this.emit('hit',f.x,f.z,'Dark bombs bite. Dodge their red landing rings.');if(this.hearts<=0)this.finish(false,'Three bomb bumps. Keep your basket closed when running away.');}else this.emit('pop',f.x,f.z);continue;}if(close&&this.action){f.done=true;const requested=this.request===null||f.kind==='gold'||f.type===this.request;if(requested){this.combo++;this.bestCombo=Math.max(this.bestCombo,this.combo);this.score+=f.kind==='gold'?3:f.kind==='cherry'?2:1;this.score+=this.combo%3===0?1:0;this.requestCount++;if(this.request!==null&&this.requestCount>=3){this.request=1-this.request;this.requestCount=0;}this.emit('collect',f.x,f.z,this.combo>=3?'Sweet streak ×'+this.combo:'Lovely catch!');}else{this.combo=0;this.emit('notice',f.x,f.z,'Catch the requested '+(this.request===0?'peach':'blueberry')+'.');}if(f.kind==='ice'){this.slow=2.3;this.emit('notice',f.x,f.z,'Icy feet · 2 seconds');}if(this.score>=this.total)this.finish(true);}else if(this.index>=5&&!f.bounced){f.bounced=true;f.age=0;f.duration=1.15;f.startX=f.x;f.startZ=f.z;this.emit('bounce',f.x,f.z);}else{f.done=true;this.combo=0;this.emit('miss',f.x,f.z);}}this.fruit=this.fruit.filter(f=>!f.done||f.age<f.duration+.15);}
 waypoint(){if(this.mode===0)return this.near||{x:0,z:0};if(this.mode===1)return gardenPoint(this.garden.mirrors.find(q=>q.id===this.selected));if(this.mode===2)return this.cages.find(q=>!q.freed)||this.exit;if(this.mode===3)return this.course.gates[this.score]||this.course.start;return this.fruit.filter(q=>!q.done&&q.kind!=='bomb').sort((a,b)=>(a.duration-a.age)-(b.duration-b.age))[0]||this.player;}
 hud(){if(this.mode===0){const n=this.near;let hint=this.hand?.ready?'SERVE '+this.hand.recipe.name:this.hand?'TAKE TO '+(!this.hand.chopped?'PREP':['PAN','NOODLES','SOUP'][this.hand.recipe.cooker]):'TAKE AN INGREDIENT';return {goal:`${this.score} / ${this.total} guests`,meter:this.hand?this.hand.recipe.name+(this.hand.ready?' · READY':' · RAW'):'HANDS FREE',fill:this.prep/1.4,hint:n?hint+' · '+n.kind.toUpperCase():'MOVE TO A STATION',extra:this.orders.filter(q=>q.active&&!q.done).map(q=>({label:RECIPES[q.type].name,value:clamp(q.patience/43),color:RECIPES[q.type].color})),lives:4-this.mistakes};}if(this.mode===1)return {goal:`${this.score} / ${this.total} blooms`,meter:`${this.moves} turns · par ${this.par}`,fill:this.bloom/1.1,hint:this.index<5?'TAP A MIRROR TO TURN THE BEAM':this.garden.shutter&&!this.shutterOpen?'TAP THE SUN SWITCH TO OPEN THE SHUTTER':'MATCH THE BEAM TO THE FLOWER COLOR',extra:[],lives:0};if(this.mode===2)return {goal:`${this.score} / ${this.total} rescued`,meter:this.hidden?'HIDDEN':this.seen?'WATCH OUT':'QUIET PAWS',fill:this.alarm,hint:this.score>=this.total?'ALL SAFE · FIND THE EXIT':this.index>=3&&!this.key.taken?'FIND THE KEY · HOLD TO RESCUE':'HOLD NEAR A CAGE TO RESCUE',extra:[],lives:3-this.strikes};if(this.mode===3)return {goal:`${this.score} / ${this.total} gates`,meter:this.boost>0?'TURBO!':this.charge>.05?`DRIFT ${Math.round(this.charge*100)}%`:this.surface.toUpperCase(),fill:this.charge,hint:'GATES IN ORDER · HOLD IN TURNS, RELEASE FOR TURBO',extra:[],lives:0};return {goal:`${this.score} / ${this.total} points`,meter:this.combo?`STREAK ×${this.combo}`:'READY TO CATCH',fill:this.combo%3/3,hint:this.request!==null?'CATCH '+(this.request===0?'PEACHES':'BLUEBERRIES')+' · GOLD IS ALWAYS GOOD':'HOLD TO CATCH · LET GO TO RUN',extra:[],lives:this.hearts};}
}
