export const STARTS=[
 {layout:'bento',brand:'MOMO’S',club:'LUNCH CLUB',mark:'m.',eyebrow:'MOMO’S LUNCH CLUB',start:'OPEN THE KITCHEN',route:'Pick today’s menu.',chapters:'BREAKFAST → LUNCH → RUSH',pause:'Kitchen on a break.',note:'Your pans and guests can wait a moment.'},
 {layout:'garden',brand:'LUMA’S',club:'LITTLE GARDEN',mark:'✧',eyebrow:'A LITTLE LIGHT. A LITTLE MAGIC.',start:'WAKE THE GARDEN',route:'Follow the flower trail.',chapters:'BUD → BEAM → BLOOM',pause:'Let the light rest.',note:'Every reflection will be right here when you return.'},
 {layout:'heist',brand:'POCKET',club:'RESCUE SOCIETY',mark:'r.',eyebrow:'THE POCKET RESCUE SOCIETY',start:'BEGIN THE RESCUE',route:'Choose a rescue file.',chapters:'SCOUT → RESCUE → ESCAPE',pause:'Keep a low profile.',note:'The patrols are paused. Plan your next quiet move.'},
 {layout:'race',brand:'PIP’S',club:'RACE CLUB',mark:'01',eyebrow:'THE TINY WHEELS CHAMPIONSHIP',start:'START YOUR ENGINES',route:'Choose your circuit.',chapters:'LEARN → DRIFT → MASTER',pause:'A little pit stop.',note:'The race clock is stopped. Your kart is ready when you are.'},
 {layout:'party',brand:'PEPO’S',club:'FRUIT FESTIVAL',mark:'p.',eyebrow:'PEPO’S FRUIT FESTIVAL',start:'LET’S CATCH!',route:'Pick a party ticket.',chapters:'PEACH → MIX → CARNIVAL',pause:'Save your party spot.',note:'The fruit shower is paused. Your basket can take a breather.'}
];
const heading=()=>'<span id="menu-kicker" class="kicker"></span><h1 id="game-title"></h1><p id="tagline"></p>';
const art=(extra='')=>`<div class="menu-art ${extra}"><span id="genre" class="art-genre"></span><div id="menu-preview" class="menu-preview"></div><div class="art-caption"><span id="animal"></span></div></div>`;
const level=(label)=>`<div class="level-selector"><button id="previous-level" class="round-button" aria-label="Previous level">←</button><button id="choose-level" class="selected-level"><span id="chapter"></span><strong id="level-number"></strong><small>${label} ↗</small></button><button id="following-level" class="round-button" aria-label="Next level">→</button></div>`;
const mission=(label)=>`<div class="mission"><span class="kicker">${label}</span><h2 id="level-title"></h2><p id="level-feature"></p><span id="best-stars" class="best-stars"></span></div>`;
const start=(mode)=>`<button id="start" class="primary">${STARTS[mode].start}<span>↗</span></button>`;
const footer=()=>'<footer class="start-footer"><details class="start-help"><summary>HOW TO PLAY</summary><p id="help"></p></details><a id="back-hub" class="text-link" href="./">EXPLORE ALL FIVE WORLDS</a></footer>';
const icon=(kind)=>({key:'<svg viewBox="0 0 48 48" aria-hidden="true"><circle cx="15" cy="17" r="9"/><path d="m21 24 17 17m-6-6 6-6m-13-1 6-6"/></svg>',duck:'<svg viewBox="0 0 48 48" aria-hidden="true"><path d="M7 29c0 11 28 15 33 1l-8-2c6-15-13-24-16-11-2 5 0 9 3 11Z"/><path d="m31 17 10 4-10 4"/><circle cx="26" cy="16" r="1"/></svg>',exit:'<svg viewBox="0 0 48 48" aria-hidden="true"><path d="M9 42V7h26v35M20 25h23m-8-8 8 8-8 8"/></svg>'}[kind]);

export function mountStart(mode,element){
 element.className=`menu start-screen ${STARTS[mode].layout}-menu`;
 element.dataset.layout=STARTS[mode].layout;
 const templates=[
  `<header class="bento-brand">${heading()}<span class="open-stamp">MADE WITH<br>HAPPY PAWS</span></header><div class="bento-display">${art('kitchen-window')}<div class="restaurant-sign">FRESH • LITTLE • DELICIOUS</div></div><div class="receipt"><div class="receipt-heading"><span>TODAY’S ORDER</span><b>NO. 01—15</b></div>${mission('ON THE MENU')}${level('CHOOSE A SHIFT')}<div class="receipt-total"><span>ONE LITTLE CHEF</span><b>LOTS OF HAPPY GUESTS</b></div>${start(0)}</div>${footer()}`,
  `<header class="garden-heading">${heading()}</header><div class="garden-display"><span class="garden-spark spark-one">✧</span><span class="garden-spark spark-two">✧</span>${art('garden-arch')}<div class="garden-message">TURN LIGHT INTO LIFE</div></div><div class="garden-trail">${level('EXPLORE THE GARDENS')}</div><div class="garden-invitation">${mission('YOUR NEXT BLOOM')}${start(1)}</div>${footer()}`,
  `<div class="case-folder"><div class="case-tab">FIELD NOTES / KEEP IT QUIET</div><div class="heist-board"><header class="brief-heading">${heading()}<div class="case-stamp">LITTLE PAWS<br>BIG MISSION</div></header><div class="mugshot">${art('agent-photo')}<span class="photo-tape"></span><b>AGENT RUE</b></div><div class="mission-brief">${mission('RESCUE FILE')}</div><div class="evidence-strip"><span>${icon('key')}FIND THE KEY</span><span>${icon('duck')}FREE YOUR FRIENDS</span><span>${icon('exit')}GET HOME SAFE</span></div></div><div class="operation-picker">${level('OPEN RESCUE FILE')}</div>${start(2)}</div>${footer()}`,
  `<div class="race-poster"><div class="race-checker"></div><header class="race-heading">${heading()}</header>${art('pit-stage')}<div class="race-callout"><b>HOLD THE DRIFT.</b><span>RELEASE THE TURBO.</span></div><div class="race-number" aria-hidden="true">01</div></div><div class="race-console"><div class="race-plan">${mission('NEXT CIRCUIT')}${level('PICK YOUR GRID')}</div>${start(3)}</div>${footer()}`,
  `<header class="party-heading">${heading()}<span class="party-confetti confetti-one">✦</span><span class="party-confetti confetti-two">✦</span></header><div class="party-display">${art('fruit-stage')}<div class="party-sticker">CATCH A<br>LITTLE JOY!</div><span class="party-loop loop-one"></span><span class="party-loop loop-two"></span></div><div class="party-ticket"><span class="ticket-edge">ADMIT ONE LITTLE PENGUIN</span>${level('PICK A PARTY TICKET')}${mission('COMING UP NEXT')}</div><div class="party-launch">${start(4)}</div>${footer()}`
 ];
 element.innerHTML=templates[mode];
}
